### ISSUE TITLE
Comparison with Zero-Shot-CoT

### ISSUE THREAD

**Issue by AiMijie** [GasolSun36/Iter-CoT#2]
Have you made a comparison with Zero-Shot-CoT?

**Comment by GasolSun36** [comment]
We didn't compare with Zero-Shot-CoT, because for mathematical reasoning, commonsense reasoning and symbolic reasoning, the effect of the Few-shot-CoT must be better than the Zero-Shot-CoT so we only did the experiments under the Few-Shot. Moreover, Iter-CoT is more focused on finding the most suitable exemplars.

**Comment by AiMijie** [comment]
Got it. Thanks for your reply.
